### ISSUE TITLE
"date" is not an output of update-workflows

### ISSUE THREAD

**Issue by Bisaloo** [carpentries/actions#85]
"date" is not an output of the update-workflows action:

https://github.com/carpentries/actions/blob/6447b1f16e70ca28221c7225afabd0a015c178ba/update-workflows/action.yml#L16-L22

yet it is used in the update-workflows workflow present in lesson repositories:

https://github.com/swcarpentry/r-novice-inflammation/blob/60e8a595cbbd7439612258c990185cb7f88f9396/.github/workflows/update-workflows.yaml#L62

This results in missing text in the PR:

https://github.com/swcarpentry/r-novice-inflammation/pull/594

> Auto-generated by create-pull-request on

PS: this issue makes me realize that having the same name for the action defined here and the workflow in repos makes it a bit difficult to be clear on what we are talking about. Should this be changed as well?

**Comment by zkamvar** [comment]
Thank you for opening this issue @Bisaloo! This is definitely a bug that should be fixed with https://github.com/carpentries/actions/pull/86. I [added the date output parameter a year ago](https://github.com/carpentries/actions/commit/4d5577f7e628d33adb79398c601c37a8e066c2ca#diff-3521942d5b0cad0c14ae88641ca7d45d57bfd3ada5ebe50c273d8c89a4217569), but never got around to adding it as an official parameter, and it became one of the "nice to have" features as I believe I was putting out bigger fires at the time -_-

**Comment by zkamvar** [comment]
Regarding this:

> PS: this issue makes me realize that having the same name for the action defined here and the workflow in repos makes it a bit difficult to be clear on what we are talking about. Should this be changed as well?

I don't think so. I think you clearly identified the "action" vs the "workflow" component. If we were to change the name of either of them, we would change the workflow since changing the name of the action would be quite disruptive.
